language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#CI 서버 home

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#CI 실행 완료시 메일 알람

notifications:
  email:
    recipients:
      - 'jhlee7129@naver.com'

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

#s3 access_key, secret_key, 제공자, 버킷, 지역등 명시
#zip 파일 접근 private
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-build-v1
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-webservice-build-v1
    key: springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice
    development_group: springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true